# Generated by Django 4.0.1 on 2023-06-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mem_nm', models.CharField(max_length=20)),
                ('mem_pw', models.CharField(max_length=20)),
                ('teste', models.CharField(max_length=20, null=True)),
                ('tema', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
    ]
