# Generated by Django 4.0.1 on 2023-06-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_alter_member_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('lo_lc', models.CharField(max_length=300)),
                ('lo_la', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'loging',
                'ordering': ['address'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('travel_nm', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('images', models.CharField(max_length=100)),
                ('sido', models.CharField(max_length=100)),
                ('sigungu', models.CharField(max_length=100, null=True)),
                ('travel_url', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'travel',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'managed': False},
        ),
    ]
