# Generated by Django 4.0.1 on 2023-06-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_loging_travel_alter_member_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('address', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('lo_la', models.CharField(max_length=100)),
                ('lo_lc', models.CharField(max_length=100)),
                ('parking', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'PARKING_LOT',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='loging',
            options={'managed': False},
        ),
    ]
